# Generated by Django 4.2.4 on 2023-08-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('image_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.CharField(max_length=250)),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
