# Generated by Django 4.2.4 on 2023-08-13 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fruitipediaapp.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(25), fruitipediaapp.web.validators.StartWithALetter('profile')])),
                ('last_name', models.CharField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(35), fruitipediaapp.web.validators.StartWithALetter('profile')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.MaxLengthValidator(40)])),
                ('password', models.CharField(validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(20)])),
                ('image_url', models.URLField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(30), fruitipediaapp.web.validators.StartWithALetter('fruit')])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('nutrition', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.profile')),
            ],
        ),
    ]
